spring.application.name=learning-platform

# MySQL Database Connection
spring.datasource.url=jdbc:mysql://localhost:3306/learning_db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=Srn@csk49

# Hibernate Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Gemini API Key 
gemini.api.key=AIzaSyBI3YE5nLUks3uHTUOy9k75Mwrcj3LCGwo
# MySQL Database Connection
spring.datasource.url=jdbc:mysql://localhost:3306/ai_platform
spring.datasource.username=root
spring.datasource.password=Srn@csk49
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true