# Port setup for Render
server.port=${PORT:8080}

# PostgreSQL Database Settings
spring.datasource.url=postgresql://learning_platform_db_o1lm_user:PKuoXCsgslmIzO4fW8ZAAK5AScgMgAzT@dpg-d776vnidbo4c73eajl80-a.oregon-postgres.render.com/learning_platform_db_o1lm
spring.datasource.username=learning_platform_db_o1lm_user
spring.datasource.password=PKuoXCsgslmIzO4fW8ZAAK5AScgMgAzT

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Gemini API Key
gemini.api.key=${GEMINI_API_KEY}